[package]
name = "pre-commit-dag"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
pre-commit-core = { workspace = true }
petgraph = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
