name: Example Usage

# This workflow demonstrates how to use pre-commit-rs in CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup pre-commit-ci
        uses: ./.github/actions/setup-pre-commit

      - name: Run hooks with JSON output
        run: |
          ./pre-commit-ci --parallel --format json > results.json
          cat results.json

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pre-commit-results
          path: results.json
