name: Test

on:
  workflow_call:

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      - name: Setup pre-commit-ci
        uses: ./.github/actions/setup-pre-commit

      - name: Run pre-commit hooks
        run: ./pre-commit-ci --parallel
